package charactermaker.model.items;

import charactermaker.model.items.armor.*;
import charactermaker.model.items.gear.*;
import charactermaker.model.items.weapons.*;
import java.util.*;

public class Items {
	private List<Items> items;
	private List<Armor> armor;
	private List<Gear> gear;
	private List<Weapons> weapons;
	public Items() {
		items = new ArrayList<Items>();
		armor = new ArrayList<Armor>();
		armor.add(new Breastplate());
		armor.add(new ChainMail());
		armor.add(new ChainShirt());
		armor.add(new HalfPlate());
		armor.add(new Hide());
		armor.add(new Leather());
		armor.add(new Padded());
		armor.add(new Plate());
		armor.add(new RingMail());
		armor.add(new ScaleMail());
		armor.add(new Shield());
		armor.add(new Splint());
		armor.add(new StuddedLeather());
		gear = new ArrayList<Gear>();
		gear.add(new Abacus());
		gear.add(new Acid_vial());
		gear.add(new AlchemistsFire_flask());
		gear.add(new Amulet());
		gear.add(new Antitoxin_vial());
		gear.add(new Arrows());
		gear.add(new Backpack());
		gear.add(new BallBearings_bag1000());
		gear.add(new Barrel());
		gear.add(new Basket());
		gear.add(new Bedroll());
		gear.add(new Bell());
		gear.add(new Blanket());
		gear.add(new BlockAndTackle());
		gear.add(new BlowgunNeedles());
		gear.add(new Book());
		gear.add(new Bucket());
		gear.add(new BullseyeLantern());
		gear.add(new Caltrops_bag20());
		gear.add(new Candle());
		gear.add(new Chain_10ft());
		gear.add(new Chalk());
		gear.add(new Chest());
		gear.add(new ClimbersKit());
		gear.add(new CommonClothes());
		gear.add(new ComponentPouch());
		gear.add(new CostumeClothes());
		gear.add(new CrossbowBoltCase());
		gear.add(new CrossbowBolts());
		gear.add(new Crowbar());
		gear.add(new Crystal());
		gear.add(new Emblem());
		gear.add(new FineClothes());
		gear.add(new FishingTackle());
		gear.add(new GlassBottle());
		gear.add(new GrapplingHook());
		gear.add(new Hammer());
		gear.add(new HealersKit());
		gear.add(new HempenRope_50ft());
		gear.add(new HolyWater_flask());
		gear.add(new HoodedLantern());
		gear.add(new Hourglass());
		gear.add(new HuntingTrap());
		gear.add(new Ink());
		gear.add(new InkPen());
		gear.add(new IronPot());
		gear.add(new IronSpikes_10());
		gear.add(new Jug());
		gear.add(new Ladder_10ft());
		gear.add(new Lamp());
		gear.add(new Lock());
		gear.add(new MagnifyingGlass());
		gear.add(new Manacles());
		gear.add(new MapScrollCase());
		gear.add(new MerchantsScale());
		gear.add(new MessKit());
		gear.add(new MinersPick());
		gear.add(new Mirror());
		gear.add(new Oil_flask());
		gear.add(new Orb());
		gear.add(new Paper());
		gear.add(new Parchment());
		gear.add(new Perfume());
		gear.add(new Piton());
		gear.add(new Poison_flask());
		gear.add(new Pole_10ft());
		gear.add(new PortableRam());
		gear.add(new PotionOfHealing());
		gear.add(new Pouch());
		gear.add(new Quiver());
		gear.add(new Rations_1day());
		gear.add(new Reliquary());
		gear.add(new Robes());
		gear.add(new Rod());
		gear.add(new Sack());
		gear.add(new SealingWax());
		gear.add(new Shovel());
		gear.add(new SignalWhistle());
		gear.add(new SignetRing());
		gear.add(new SilkRope_50ft());
		gear.add(new SledgeHammer());
		gear.add(new SligBullets());
		gear.add(new Soap());
		gear.add(new Spellbook());
		gear.add(new SprigOfMisltetoe());
		gear.add(new Spyglass());
		gear.add(new Staff());
		gear.add(new Tankard());
		gear.add(new Tent());
		gear.add(new Tinderbox());
		gear.add(new Torch());
		gear.add(new Totem());
		gear.add(new TravelersClothes());
		gear.add(new Vial());
		gear.add(new Wand());
		gear.add(new Waterskin());
		gear.add(new Whetstone());
		gear.add(new WoodenStaff());
		gear.add(new YewWand());
		weapons = new ArrayList<Weapons>();
		weapons.add(new Battleaxe());
		weapons.add(new Blowgun());
		weapons.add(new Club());
		weapons.add(new CrossbowHand());
		weapons.add(new CrossbowHeavy());
		weapons.add(new CrossbowLight());
		weapons.add(new Dagger());
		weapons.add(new Dart());
		weapons.add(new Flail());
		weapons.add(new Glaive());
		weapons.add(new Greataxe());
		weapons.add(new Greatclub());
		weapons.add(new Greatsword());
		weapons.add(new Halberd());
		weapons.add(new Handaxe());
		weapons.add(new Javelin());
		weapons.add(new Lance());
		weapons.add(new LightHammer());
		weapons.add(new Longbow());
		weapons.add(new Longsword());
		weapons.add(new Mace());
		weapons.add(new Maul());
		weapons.add(new Morningstar());
		weapons.add(new Net());
		weapons.add(new Pike());
		weapons.add(new Quarterstaff());
		weapons.add(new Rapier());
		weapons.add(new Scimitar());
		weapons.add(new Shortbow());
		weapons.add(new Shortsword());
		weapons.add(new Sickle());
		weapons.add(new Sling());
		weapons.add(new Spear());
		weapons.add(new Trident());
		weapons.add(new Warhammer());
		weapons.add(new WarPick());
		weapons.add(new Whip());
		
		for (Armor armor : armor) {
			items.add(armor);
		}
		for (Gear gear : gear) {
			items.add(gear);
		}
		for (Weapons weapons : weapons) {
			items.add(weapons);
		}
	}
	public List<Items> getItems() {
		return items;
	}
}
